### ISSUE TITLE
Nginx bad gateway

### ISSUE THREAD

**Issue by danymar24** [githubsaturn/meteor-captainduckduck#1]
Issue: Nginx Bad gateway
Host: Digitalocean
OS: Ubuntu Docker 17.12

I am deploying a meteor 1.6.0 application with the sample captain-definition file, the build finishes successfully but i am receiving 502 Bad gateway.

Anybody is getting this error?

**Comment by githubsaturn** [comment]
You can run `docker service logs srv-captain--my-app-name` to see logs of your app. You app probably is failing to start up properly. Note that you need to replace `my-app-name` with your own app name.

**Comment by danymar24** [comment]
Thanks for the answer, i entered the command and its giving me the issue: 
![image](https://user-images.githubusercontent.com/4708058/35689987-6a4ab808-073a-11e8-9834-1808e0fe74d4.png)

I searched it and some people says its due to the nodejs version, i tried using 8.9.4 and 9.5.0 but its still not working, do you know waht else can i do @githubsaturn?

**Comment by githubsaturn** [comment]
It is indeed related to Node version. Can you retry using this captain-definition:

```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM abernix/meteord:node-8.9.1-base",
    "ENV NODE_VERSION 8.9.1",
    "RUN bash $METEORD_DIR/lib/install_meteor.sh",
    "COPY ./src /app",
    "RUN bash $METEORD_DIR/lib/build_app.sh"
  ]
}
```

**Comment by danymar24** [comment]
Thanks @githubsaturn that solved the issue.
