### ISSUE TITLE
Deploying meteor app to Captain

### ISSUE THREAD

**Issue by Salamit** [githubsaturn/meteor-captainduckduck#2]
Hi, I'm trying to replicate the deployment process to deploy my app to captainduckduck but I'm getting the the following error:

`Something bad happened. Cannot deploy "[app-name]"`

This is the full error
```
Deploy failed!
Error: {"code":1,"message":"The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1"}
The command '/bin/sh -c npm install && npm cache clean --force' returned a non-zero code: 1
```

My captain definition file looks like this:
```
{
  "schemaVersion": 1,
  "dockerfileLines": [
    "FROM abernix/meteord:node-8.11.2-base",
    "ENV NODE_VERSION 8.11.3",
    "RUN bash $METEORD_DIR/lib/install_meteor.sh",
    "COPY ./src /app",
    "RUN bash $METEORD_DIR/lib/build_app.sh"
  ]
}
```

Any help is greatly appreciated. Thanks in advance.

**Comment by githubsaturn** [comment]
Most likely, your container is running out of memory. See this IMPORTANT NOTE:
https://github.com/githubsaturn/meteor-captainduckduck#important-notes
