### ISSUE TITLE
Question: Meteor mongo path

### ISSUE THREAD

**Issue by bilicio** [githubsaturn/meteor-captainduckduck#4]
Hi kasra!

How meteor knows where to find and use this mongo database when you set this environment variable?

ROOT_URL http://meteortest.captainrootdomain.domain.com
MONGO_URL mongodb://<USERNAME>:<PASSWORD>@srv-captain--meteor-test-db:27017/test-meteor?authSource=admin

Meteor automaticly looks for this ENV_VARIABLE to know the path?

thank you!

**Comment by githubsaturn** [comment]
It's a meteor env var:
https://docs.meteor.com/environment-variables.html#MONGO-URL

**Comment by bilicio** [comment]
oh! i see.. thank you! by the way. love it caprover,  it gets better every update!! good job!! :)
